#!/bin/sh

APP_NAME=car-dashboard

CLUSTER_NAME=$APP_NAME
CLUSTER_LOCATION=syd01
CLUSTER_WORKERS=2
CLUSTER_MC_TYPE=u1c.2x4
CLUSTER_HARDWARE=shared

VLAN_PRIV=priv01
VLAN_PUB=pub01

#KUBE_NAMESPACE=$APP_NAME
KUBE_NAMESPACE=default

REGISTRY=registry.au-syd.bluemix.net
REGISTRY_NAMESPACE=iwinoto_gmail_funfactory
IMAGE_NAME=$APP_NAME
